version: '3.8'

#######################################################
# ESTE TIPO DE ARCHIVO SE SEPARA POR TABULACIONES .l.
#######################################################
services:
  mysql_db:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: papu0812AC
      MYSQL_DATABASE: eventos_db
    ports:
      - "3307:3306" #EL PUERTO DE LA IZQ ES EL INTERNO, EL OTRO ES EL PUERTO DONDE SE EJECUTA MYSQL
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
